<?php

include_once('ec_partners.features.inc');


/**
 * Implementation of hook_init().
 */
function ec_partners_init() {
  drupal_add_css(drupal_get_path('module', 'ec_partners') .'/ec_partners.css');
}

/**
 * Implementation of hook_menu_alter()
 */
function ec_partners_menu_alter(&$items) {
  $items['node/add/partner']['title'] = t('Add a University');
}

/**
 * Implementation of hook_openlayers_alter()
 */
function ec_partners_openlayers_alter($map) {

  global $base_url;
  foreach (array('partners_openlayers_1', 'partners_openlayers_2') as $layer) {
    if (isset($map['layers'][$layer])) {
      foreach ($map['layers'][$layer]['features'] as $key => $feature) {
        $marker = $feature['attributes']['node_data_field_partner_location_field_partner_marker_value'];
        $marker = $marker ? $marker : 'marker_01.png';
        $path = ($layer == 'partners_openlayers_2') ? '32/' : '48/';
        $image = drupal_get_path('module', 'ec_partners') .'/images/'. $path . $marker;
        $size = @getimagesize($image);

        $feature['style']['pointRadius'] = 3;
        $feature['style']['strokeWidth'] = 0;
        $feature['style']['externalGraphic'] = $base_url .'/'. $image;
        $feature['style']['graphicWidth'] = $size[0];
        $feature['style']['graphicHeight'] = $size[1];
        $feature['style']['graphicYOffset'] = -$size[1] + 5;
        $feature['style']['graphicOpacity'] = 1;

        $map['layers'][$layer]['features'][$key] = $feature;
      }
    }
  }
}

/**
 * Implementation of hook_node_form_sidebar()
 */
function ec_partners_node_form_sidebar(&$form, &$form_state) {
  if ($form['type']['#value'] == 'partner') {
    return array(
      'field_partner_marker',
      'field_partner_order',
      'field_partner_logo',
      'taxonomy',
    );
  }
}

/**
 * Implementation of hook_theme_registry_alter()
 */
function ec_partners_theme_registry_alter(&$theme_registry) {

  foreach (array('views_view_fields__partners__attachment_1', 'views_view_fields__partners__page_1') as $hook) {
    $theme_registry[$hook] = $theme_registry['views_view_fields'];
    $theme_registry[$hook]['file'] = NULL;
    $theme_registry[$hook]['template'] = views_css_safe($hook);
    $theme_registry[$hook]['path'] = drupal_get_path('module', 'ec_partners') . '/theme';
  }

  foreach (array('views_view_field__partners__attachment_1__field_partner_marker_value', 'views_view_field__field_partner_marker_value') as $hook) {
    $theme_registry[$hook] = $theme_registry['views_view_field'];
    $theme_registry[$hook]['function'] = $theme_registry[$hook]['file'] = NULL;
    $theme_registry[$hook]['template'] = views_css_safe($hook);
    $theme_registry[$hook]['path'] = drupal_get_path('module', 'ec_partners') . '/theme';
  }

  $hook = 'views_view__partners__block_3';
  $theme_registry[$hook] = $theme_registry['views_view'];
  $theme_registry[$hook]['function'] = $theme_registry[$hook]['file'] = NULL;
  $theme_registry[$hook]['template'] = views_css_safe($hook);
  $theme_registry[$hook]['path'] = drupal_get_path('module', 'ec_partners') . '/theme';

  $theme_registry['content_field']['theme paths'][] = drupal_get_path('module', 'ec_partners') .'/theme';
}
